### PR TITLE
 Create Hello-rails-react app

### PR DESCRIPTION
**Pull request by Yacoubou-seidou**
## Create Hello-rails-react app
- Use the correct name
- `jsbundling-rails` gem installed
- Create `babel.config.js` file
- create an API endpoint that selects a random greeting
- create a static view
- create App component with react-router
- Create a store, an action, and a reducer that will connect to the API endpoint to get the random greeting.
- Display the random greeting in the Greeting component.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @Yacoubou-seidou,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Backend data renders ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] While you have all the required setup and the backend data renders, I think there is an issue with your webpack setup which makes the frontend to throw errors, when I run the server, I get this error attached in the image, and I tried precompiling the assets with `rails assets:precompile` but I get errors as regards webpack.
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yacoubou-seidou** [comment]
@Olamarx Hello kindly run the command 'dev' to run the app i also add that in the readme file

**Review by Nemwel-Boniface — COMMENTED** [review]
## Hello  @Yacoubou-seidou  👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request with a complaint about the previous reviewer @Olamarx . Below are my findings:


I also seem to be getting a similar error to the one the previous reviewer @Olamarx  was facing. To try and make it more fair, I had to ask a few people to test your project and we all faced the same error.

Screenshot from 2023-08-17 18-31-29


**What you should do:**

Even though your project might be working on your end, you also need to ensure that other people are able to test your project. This would include ensuring that if you did something/ used a specific command when setting your project, you also need to ensure that the same same detailed steps are included for others to be able to test your project locally.

Kindly ensure that your project works and is testable by other people by updating your REDAME with a detailed step to test it.




In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

**Review by julie-ify — APPROVED** [review]
Hi @Yacoubou-seidou,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
